"""
Unit tests for the scanner.analysis module.
"""

import pandas as pd
import pytest
from pandas import Timestamp

from config import settings
from scanner.analysis import calculate_smas, check_golden_cross, check_approaching_golden_cross


@pytest.fixture
def sample_stock_data():
    """
    Creates a sample DataFrame with stock price data.
    """
    # Create a DataFrame with 300 days of sample data
    # This is enough for both 50-day and 200-day SMAs
    dates = pd.date_range(start="2023-01-01", periods=300, freq="D")
    
    # Create a DataFrame with a simple price pattern
    # Prices start at 100 and increase by 0.1 each day
    df = pd.DataFrame(
        {
            "Open": [100 + i * 0.1 for i in range(300)],
            "High": [101 + i * 0.1 for i in range(300)],
            "Low": [99 + i * 0.1 for i in range(300)],
            "Close": [100 + i * 0.1 for i in range(300)],
            "Volume": [1000000 for _ in range(300)],
        },
        index=dates,
    )
    
    return df


@pytest.fixture
def golden_cross_data():
    """
    Creates a DataFrame with a golden cross pattern.
    
    The 50-day SMA crosses above the 200-day SMA on the last day.
    """
    dates = pd.date_range(start="2023-01-01", periods=250, freq="D")
    
    # Create a price pattern where:
    # - Prices start at 100
    # - Decline for a while (causing 50-day SMA to be below 200-day SMA)
    # - Then rise sharply (causing 50-day SMA to cross above 200-day SMA)
    
    # First 150 days: price declines from 100 to 80
    decline_rate = (80 - 100) / 150
    first_segment = [100 + i * decline_rate for i in range(150)]
    
    # Next 100 days: price rises from 80 to 120
    rise_rate = (120 - 80) / 100
    second_segment = [80 + i * rise_rate for i in range(100)]
    
    # Combine the segments
    close_prices = first_segment + second_segment
    
    df = pd.DataFrame(
        {
            "Close": close_prices,
            # Add other columns for completeness
            "Open": close_prices,
            "High": [p + 1 for p in close_prices],
            "Low": [p - 1 for p in close_prices],
            "Volume": [1000000 for _ in range(250)],
        },
        index=dates,
    )
    
    # Pre-calculate the SMAs for testing
    short_window = settings.SHORT_SMA_WINDOW
    long_window = settings.LONG_SMA_WINDOW
    
    # Calculate initial SMAs (needed for non-NaN values earlier in the series)
    df[f"SMA_{short_window}"] = df["Close"].rolling(window=short_window).mean()
    df[f"SMA_{long_window}"] = df["Close"].rolling(window=long_window).mean()

    # Manually set the last two days' SMAs to force the golden cross condition
    # Ensure we have enough non-NaN rows before attempting iloc
    valid_rows = df.dropna(subset=[f"SMA_{short_window}", f"SMA_{long_window}"])
    if len(valid_rows) >= 2:
        # Day -2 (Yesterday): SMA_50 <= SMA_200
        df.iloc[-2, df.columns.get_loc(f"SMA_{short_window}")] = 90.0
        df.iloc[-2, df.columns.get_loc(f"SMA_{long_window}")] = 91.0
        # Day -1 (Today): SMA_50 > SMA_200
        df.iloc[-1, df.columns.get_loc(f"SMA_{short_window}")] = 92.0
        df.iloc[-1, df.columns.get_loc(f"SMA_{long_window}")] = 91.5
    else:
        # This case should ideally not happen with 250 periods, but handle defensively
        pytest.skip("Insufficient valid SMA data generated by fixture to manually set cross condition.")

    return df


@pytest.fixture
def no_cross_data():
    """
    Creates a DataFrame without a golden cross pattern.
    
    The 50-day SMA remains below the 200-day SMA.
    """
    dates = pd.date_range(start="2023-01-01", periods=250, freq="D")
    
    # Create a price pattern where:
    # - Prices start at 100
    # - Decline consistently (keeping 50-day SMA below 200-day SMA)
    
    # 250 days: price declines from 100 to 70
    decline_rate = (70 - 100) / 250
    close_prices = [100 + i * decline_rate for i in range(250)]
    
    df = pd.DataFrame(
        {
            "Close": close_prices,
            # Add other columns for completeness
            "Open": close_prices,
            "High": [p + 1 for p in close_prices],
            "Low": [p - 1 for p in close_prices],
            "Volume": [1000000 for _ in range(250)],
        },
        index=dates,
    )
    
    # Pre-calculate the SMAs for testing
    short_window = settings.SHORT_SMA_WINDOW
    long_window = settings.LONG_SMA_WINDOW
    
    df[f"SMA_{short_window}"] = df["Close"].rolling(window=short_window).mean()
    df[f"SMA_{long_window}"] = df["Close"].rolling(window=long_window).mean()
    
    return df


@pytest.fixture
def approaching_cross_data():
    """
    Creates a DataFrame with a pattern approaching a golden cross.
    
    The 50-day SMA is below but within threshold% of the 200-day SMA
    and has been trending upward.
    """
    dates = pd.date_range(start="2023-01-01", periods=250, freq="D")
    
    # Create a price pattern where:
    # - Prices start at 100
    # - Decline for a while (causing 50-day SMA to be below 200-day SMA)
    # - Then rise, but not enough to cross yet
    
    # First 150 days: price declines from 100 to 80
    decline_rate = (80 - 100) / 150
    first_segment = [100 + i * decline_rate for i in range(150)]
    
    # Next 100 days: price rises from 80 to 110 (not enough to cross yet)
    rise_rate = (110 - 80) / 100
    second_segment = [80 + i * rise_rate for i in range(100)]
    
    # Combine the segments
    close_prices = first_segment + second_segment
    
    df = pd.DataFrame(
        {
            "Close": close_prices,
            # Add other columns for completeness
            "Open": close_prices,
            "High": [p + 1 for p in close_prices],
            "Low": [p - 1 for p in close_prices],
            "Volume": [1000000 for _ in range(250)],
        },
        index=dates,
    )
    
    # Pre-calculate the SMAs for testing
    short_window = settings.SHORT_SMA_WINDOW
    long_window = settings.LONG_SMA_WINDOW
    
    # Calculate initial SMAs
    df[f"SMA_{short_window}"] = df["Close"].rolling(window=short_window).mean()
    df[f"SMA_{long_window}"] = df["Close"].rolling(window=long_window).mean()
    
    # Manually set the last few days' SMAs to create the approaching cross condition
    # Ensure we have enough non-NaN rows before attempting iloc
    valid_rows = df.dropna(subset=[f"SMA_{short_window}", f"SMA_{long_window}"])
    if len(valid_rows) >= settings.TREND_DAYS + 1:
        # Set the long SMA value
        long_sma_value = 100.0
        
        # Set the short SMA values to be rising but still below long SMA
        # The gap should be within the threshold percentage
        gap_pct = settings.APPROACHING_THRESHOLD / 2  # Half the threshold for a clear test
        gap = long_sma_value * (gap_pct / 100)
        
        # Set values for the last TREND_DAYS+1 days
        for i in range(settings.TREND_DAYS + 1):
            day_index = -settings.TREND_DAYS - 1 + i
            # Short SMA rises each day but stays below long SMA
            short_sma = long_sma_value - gap + (i * gap / settings.TREND_DAYS / 2)
            df.iloc[day_index, df.columns.get_loc(f"SMA_{short_window}")] = short_sma
            df.iloc[day_index, df.columns.get_loc(f"SMA_{long_window}")] = long_sma_value
    else:
        # This case should ideally not happen with 250 periods, but handle defensively
        pytest.skip("Insufficient valid SMA data generated by fixture to manually set approaching cross condition.")
    
    return df


def test_calculate_smas_with_sufficient_data(sample_stock_data):
    """
    Tests SMA calculation with sufficient data.
    """
    # Calculate SMAs
    result_df = calculate_smas(sample_stock_data)
    
    # Check that SMA columns were added
    short_window = settings.SHORT_SMA_WINDOW
    long_window = settings.LONG_SMA_WINDOW
    
    assert f"SMA_{short_window}" in result_df.columns
    assert f"SMA_{long_window}" in result_df.columns
    
    # Check that NaN values are present for the first N-1 rows
    # (where N is the window size)
    assert result_df[f"SMA_{short_window}"].iloc[:short_window-1].isna().all()
    assert result_df[f"SMA_{long_window}"].iloc[:long_window-1].isna().all()
    
    # Check that values are calculated correctly for a few points
    # For a simple linear price increase, the SMA should be the average
    # of the window, which is the middle point's value
    
    # For 50-day SMA at day 75, it should be close to the price at day 50
    # (since prices increase linearly)
    expected_short_sma = 102.55 # Average of prices from index 1 to 50
    assert abs(result_df[f"SMA_{short_window}"].iloc[short_window] - expected_short_sma) < 0.01
    
    # For 200-day SMA at day 250, it should be close to the price at day 150
    expected_long_sma = 110.05 # Average of prices from index 1 to 200
    assert abs(result_df[f"SMA_{long_window}"].iloc[long_window] - expected_long_sma) < 0.01


def test_calculate_smas_with_insufficient_data():
    """
    Tests SMA calculation with insufficient data.
    """
    # Create a small DataFrame with only 10 days of data
    # (not enough for either SMA)
    dates = pd.date_range(start="2023-01-01", periods=10, freq="D")
    df = pd.DataFrame(
        {
            "Close": [100 + i for i in range(10)],
        },
        index=dates,
    )
    
    # Calculate SMAs
    result_df = calculate_smas(df)
    
    # Check that SMA columns were added but contain NaN values
    short_window = settings.SHORT_SMA_WINDOW
    long_window = settings.LONG_SMA_WINDOW
    
    assert f"SMA_{short_window}" in result_df.columns
    assert f"SMA_{long_window}" in result_df.columns
    
    # All values should be NaN since there's not enough data
    assert result_df[f"SMA_{short_window}"].isna().all()
    assert result_df[f"SMA_{long_window}"].isna().all()


def test_calculate_smas_with_missing_close_column():
    """
    Tests SMA calculation with a DataFrame missing the 'Close' column.
    """
    # Create a DataFrame without a 'Close' column
    dates = pd.date_range(start="2023-01-01", periods=300, freq="D")
    df = pd.DataFrame(
        {
            "Open": [100 + i * 0.1 for i in range(300)],
            "High": [101 + i * 0.1 for i in range(300)],
            "Low": [99 + i * 0.1 for i in range(300)],
            # No 'Close' column
            "Volume": [1000000 for _ in range(300)],
        },
        index=dates,
    )
    
    # Calculate SMAs
    result_df = calculate_smas(df)
    
    # Check that the DataFrame is returned unmodified
    short_window = settings.SHORT_SMA_WINDOW
    long_window = settings.LONG_SMA_WINDOW
    
    assert f"SMA_{short_window}" not in result_df.columns
    assert f"SMA_{long_window}" not in result_df.columns


def test_check_golden_cross_positive(golden_cross_data):
    """
    Tests golden cross detection with data containing a cross.
    """
    # The golden_cross_data fixture has a cross on the last day
    result = check_golden_cross(golden_cross_data)
    
    # Should detect the cross
    assert result is True


def test_check_golden_cross_negative(no_cross_data):
    """
    Tests golden cross detection with data not containing a cross.
    """
    # The no_cross_data fixture has no cross
    result = check_golden_cross(no_cross_data)
    
    # Should not detect a cross
    assert result is False


def test_check_golden_cross_with_missing_sma_columns():
    """
    Tests golden cross detection with a DataFrame missing SMA columns.
    """
    # Create a DataFrame without SMA columns
    dates = pd.date_range(start="2023-01-01", periods=10, freq="D")
    df = pd.DataFrame(
        {
            "Close": [100 + i for i in range(10)],
        },
        index=dates,
    )
    
    # Check for golden cross
    result = check_golden_cross(df)
    
    # Should return False since SMA columns are missing
    assert result is False


def test_check_golden_cross_with_insufficient_data():
    """
    Tests golden cross detection with insufficient data points.
    """
    # Create a DataFrame with SMA columns but only one data point
    dates = pd.date_range(start="2023-01-01", periods=1, freq="D")
    short_window = settings.SHORT_SMA_WINDOW
    long_window = settings.LONG_SMA_WINDOW
    
    df = pd.DataFrame(
        {
            "Close": [100],
            f"SMA_{short_window}": [50],
            f"SMA_{long_window}": [40],
        },
        index=dates,
    )
    
    # Check for golden cross
    result = check_golden_cross(df)
    
    # Should return False since there's only one data point
    # (need at least two to detect a cross)
    assert result is False


def test_check_approaching_golden_cross_positive(approaching_cross_data):
    """
    Tests approaching golden cross detection with data containing an approaching cross.
    """
    # The approaching_cross_data fixture has an approaching cross pattern
    result = check_approaching_golden_cross(approaching_cross_data)
    
    # Should detect the approaching cross
    assert result is True


def test_check_approaching_golden_cross_negative(golden_cross_data):
    """
    Tests approaching golden cross detection with data containing an actual cross.
    
    When a golden cross has already occurred, it should not be considered "approaching".
    """
    # The golden_cross_data fixture has an actual cross, not an approaching one
    result = check_approaching_golden_cross(golden_cross_data)
    
    # Should not detect an approaching cross (because it's already crossed)
    assert result is False


def test_check_approaching_golden_cross_negative_far_apart(no_cross_data):
    """
    Tests approaching golden cross detection with data where SMAs are far apart.
    """
    # The no_cross_data fixture has SMAs that are far apart
    result = check_approaching_golden_cross(no_cross_data)
    
    # Should not detect an approaching cross
    assert result is False


def test_check_approaching_golden_cross_with_missing_sma_columns():
    """
    Tests approaching golden cross detection with a DataFrame missing SMA columns.
    """
    # Create a DataFrame without SMA columns
    dates = pd.date_range(start="2023-01-01", periods=10, freq="D")
    df = pd.DataFrame(
        {
            "Close": [100 + i for i in range(10)],
        },
        index=dates,
    )
    
    # Check for approaching golden cross
    result = check_approaching_golden_cross(df)
    
    # Should return False since SMA columns are missing
    assert result is False


def test_check_approaching_golden_cross_with_insufficient_data():
    """
    Tests approaching golden cross detection with insufficient data points.
    """
    # Create a DataFrame with SMA columns but fewer data points than needed for trend analysis
    dates = pd.date_range(start="2023-01-01", periods=settings.TREND_DAYS, freq="D")
    short_window = settings.SHORT_SMA_WINDOW
    long_window = settings.LONG_SMA_WINDOW
    
    df = pd.DataFrame(
        {
            "Close": [100 + i for i in range(settings.TREND_DAYS)],
            f"SMA_{short_window}": [50 + i * 0.1 for i in range(settings.TREND_DAYS)],
            f"SMA_{long_window}": [60 + i * 0.05 for i in range(settings.TREND_DAYS)],
        },
        index=dates,
    )
    
    # Check for approaching golden cross
    result = check_approaching_golden_cross(df)
    
    # Should return False since there's not enough data for trend analysis
    assert result is False


def test_check_approaching_golden_cross_not_rising():
    """
    Tests approaching golden cross detection with SMAs within threshold but not rising.
    """
    # Create a DataFrame with SMAs close together but not consistently rising
    dates = pd.date_range(start="2023-01-01", periods=settings.TREND_DAYS + 5, freq="D")
    short_window = settings.SHORT_SMA_WINDOW
    long_window = settings.LONG_SMA_WINDOW
    
    # Create short SMA values that are within threshold but not consistently rising
    long_sma_value = 100.0
    gap_pct = settings.APPROACHING_THRESHOLD / 2
    gap = long_sma_value * (gap_pct / 100)
    
    # Create fluctuating short SMA values (not consistently rising)
    short_sma_values = []
    for i in range(settings.TREND_DAYS + 5):
        # Add some oscillation to make it not consistently rising
        if i % 2 == 0:
            short_sma_values.append(long_sma_value - gap + (i * 0.1))
        else:
            short_sma_values.append(long_sma_value - gap - (i * 0.05))
    
    df = pd.DataFrame(
        {
            "Close": [100 + i for i in range(settings.TREND_DAYS + 5)],
            f"SMA_{short_window}": short_sma_values,
            f"SMA_{long_window}": [long_sma_value for _ in range(settings.TREND_DAYS + 5)],
        },
        index=dates,
    )
    
    # Check for approaching golden cross
    result = check_approaching_golden_cross(df)
    
    # Should return False since short SMA is not consistently rising
    assert result is False